#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_test_number:
  path: /test/number/{max}
  controller: App\Controller\TestController::number
  methods: GET
homepage:
  path: /home/index
  controller: App\Controller\HomeController::index
